export const stateList = [
  "Bogotá, D.C.",
  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlántico",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Córdoba",
  "Cundinamarca",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte De Santander",
  "Putumayo",
  "Quindio",
  "Risaralda",
  "San Andrés, Providencia Y Santa Catalina",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle Del Cauca",
  "Vaupés",
  "Vichada",

]

export const dataCountry = [
  {
    "state":"Bogotá, D.C.",
    "item":[
       {
          "city":"Bogotá, D.C",
          "postalCode":"11001"
       }
    ]
 },
 {
    "state":"Amazonas",
    "item":[
       {
          "city":"El Encanto",
          "postalCode":"91263"
       },
       {
          "city":"La Chorrera",
          "postalCode":"91405"
       },
       {
          "city":"La Pedrera",
          "postalCode":"91407"
       },
       {
          "city":"La Victoria",
          "postalCode":"91430"
       },
       {
          "city":"Leticia",
          "postalCode":"91001"
       },
       {
          "city":"Mirití - Paraná",
          "postalCode":"91460"
       },
       {
          "city":"Puerto Alegría",
          "postalCode":"91530"
       },
       {
          "city":"Puerto Arica",
          "postalCode":"91536"
       },
       {
          "city":"Puerto Nariño",
          "postalCode":"91540"
       },
       {
          "city":"Puerto Santander",
          "postalCode":"91669"
       },
       {
          "city":"Tarapacá",
          "postalCode":"91798"
       }
    ]
 },
 {
    "state":"Antioquia",
    "item":[
       {
          "city":"Abejorral",
          "postalCode":"05002"
       },
       {
          "city":"Abriaquí",
          "postalCode":"05004"
       },
       {
          "city":"Alejandría",
          "postalCode":"05021"
       },
       {
          "city":"Amagá",
          "postalCode":"05030"
       },
       {
          "city":"Amalfi",
          "postalCode":"05031"
       },
       {
          "city":"Andes",
          "postalCode":"05034"
       },
       {
          "city":"Angelópolis",
          "postalCode":"05036"
       },
       {
          "city":"Angostura",
          "postalCode":"05038"
       },
       {
          "city":"Anorí",
          "postalCode":"05040"
       },
       {
          "city":"Anzá",
          "postalCode":"05044"
       },
       {
          "city":"Apartadó",
          "postalCode":"05045"
       },
       {
          "city":"Arboletes",
          "postalCode":"05051"
       },
       {
          "city":"Argelia",
          "postalCode":"05055"
       },
       {
          "city":"Armenia",
          "postalCode":"05059"
       },
       {
          "city":"Barbosa",
          "postalCode":"05079"
       },
       {
          "city":"Bello",
          "postalCode":"05088"
       },
       {
          "city":"Belmira",
          "postalCode":"05086"
       },
       {
          "city":"Betania",
          "postalCode":"05091"
       },
       {
          "city":"Betulia",
          "postalCode":"05093"
       },
       {
          "city":"Briceño",
          "postalCode":"05107"
       },
       {
          "city":"Buriticá",
          "postalCode":"05113"
       },
       {
          "city":"Cáceres",
          "postalCode":"05120"
       },
       {
          "city":"Caicedo",
          "postalCode":"05125"
       },
       {
          "city":"Caldas",
          "postalCode":"05129"
       },
       {
          "city":"Campamento",
          "postalCode":"05134"
       },
       {
          "city":"Cañasgordas",
          "postalCode":"05138"
       },
       {
          "city":"Caracolí",
          "postalCode":"05142"
       },
       {
          "city":"Caramanta",
          "postalCode":"05145"
       },
       {
          "city":"Carepa",
          "postalCode":"05147"
       },
       {
          "city":"Carolina",
          "postalCode":"05150"
       },
       {
          "city":"Caucasia",
          "postalCode":"05154"
       },
       {
          "city":"Chigorodó",
          "postalCode":"05172"
       },
       {
          "city":"Cisneros",
          "postalCode":"05190"
       },
       {
          "city":"Ciudad Bolívar",
          "postalCode":"05101"
       },
       {
          "city":"Cocorná",
          "postalCode":"05197"
       },
       {
          "city":"Concepción",
          "postalCode":"05206"
       },
       {
          "city":"Concordia",
          "postalCode":"05209"
       },
       {
          "city":"Copacabana",
          "postalCode":"05212"
       },
       {
          "city":"Dabeiba",
          "postalCode":"05234"
       },
       {
          "city":"Donmatías",
          "postalCode":"05237"
       },
       {
          "city":"Ebéjico",
          "postalCode":"05240"
       },
       {
          "city":"El Bagre",
          "postalCode":"05250"
       },
       {
          "city":"El Carmen De Viboral",
          "postalCode":"05148"
       },
       {
          "city":"El Santuario",
          "postalCode":"05697"
       },
       {
          "city":"Entrerríos",
          "postalCode":"05264"
       },
       {
          "city":"Envigado",
          "postalCode":"05266"
       },
       {
          "city":"Fredonia",
          "postalCode":"05282"
       },
       {
          "city":"Frontino",
          "postalCode":"05284"
       },
       {
          "city":"Giraldo",
          "postalCode":"05306"
       },
       {
          "city":"Girardota",
          "postalCode":"05308"
       },
       {
          "city":"Gómez Plata",
          "postalCode":"05310"
       },
       {
          "city":"Granada",
          "postalCode":"05313"
       },
       {
          "city":"Guadalupe",
          "postalCode":"05315"
       },
       {
          "city":"Guarne",
          "postalCode":"05318"
       },
       {
          "city":"Guatapé",
          "postalCode":"05321"
       },
       {
          "city":"Heliconia",
          "postalCode":"05347"
       },
       {
          "city":"Hispania",
          "postalCode":"05353"
       },
       {
          "city":"Itagüí",
          "postalCode":"05360"
       },
       {
          "city":"Ituango",
          "postalCode":"05361"
       },
       {
          "city":"Jardín",
          "postalCode":"05364"
       },
       {
          "city":"La Ceja",
          "postalCode":"05376"
       },
       {
          "city":"Jericó",
          "postalCode":"05368"
       },
       {
          "city":"La Estrella",
          "postalCode":"05380"
       },
       {
          "city":"La Pintada",
          "postalCode":"05390"
       },
       {
          "city":"La Unión",
          "postalCode":"05400"
       },
       {
          "city":"Liborina",
          "postalCode":"05411"
       },
       {
          "city":"Maceo",
          "postalCode":"05425"
       },
       {
          "city":"Marinilla",
          "postalCode":"05440"
       },
       {
          "city":"Medellín",
          "postalCode":"05001"
       },
       {
          "city":"Montebello",
          "postalCode":"05467"
       },
       {
          "city":"Murindó",
          "postalCode":"05475"
       },
       {
          "city":"Mutatá",
          "postalCode":"05480"
       },
       {
          "city":"Nariño",
          "postalCode":"05483"
       },
       {
          "city":"Nechí",
          "postalCode":"05495"
       },
       {
          "city":"Necoclí",
          "postalCode":"05490"
       },
       {
          "city":"Olaya",
          "postalCode":"05501"
       },
       {
          "city":"Peñol",
          "postalCode":"05541"
       },
       {
          "city":"Peque",
          "postalCode":"05543"
       },
       {
          "city":"Pueblorrico",
          "postalCode":"05576"
       },
       {
          "city":"Puerto Berrío",
          "postalCode":"05579"
       },
       {
          "city":"Puerto Nare",
          "postalCode":"05585"
       },
       {
          "city":"Puerto Triunfo",
          "postalCode":"05591"
       },
       {
          "city":"Remedios",
          "postalCode":"05604"
       },
       {
          "city":"Retiro",
          "postalCode":"05607"
       },
       {
          "city":"Rionegro",
          "postalCode":"05615"
       },
       {
          "city":"Sabanalarga",
          "postalCode":"05628"
       },
       {
          "city":"Sabaneta",
          "postalCode":"05631"
       },
       {
          "city":"Salgar",
          "postalCode":"05642"
       },
       {
          "city":"San Andrés De Cuerquía",
          "postalCode":"05647"
       },
       {
          "city":"San Carlos",
          "postalCode":"05649"
       },
       {
          "city":"San Francisco",
          "postalCode":"05652"
       },
       {
          "city":"San Jerónimo",
          "postalCode":"05656"
       },
       {
          "city":"San José De La Montaña",
          "postalCode":"05658"
       },
       {
          "city":"San Juan De Urabá",
          "postalCode":"05659"
       },
       {
          "city":"San Luis",
          "postalCode":"05660"
       },
       {
          "city":"San Pedro De Los Milagros",
          "postalCode":"05664"
       },
       {
          "city":"San Pedro De Urabá",
          "postalCode":"San Pedro De Urabá"
       },
       {
          "city":"San Rafael",
          "postalCode":"05667"
       },
       {
          "city":"San Roque",
          "postalCode":"05670"
       },
       {
          "city":"San Vicente Ferrer",
          "postalCode":"05674"
       },
       {
          "city":"Santa Bárbara",
          "postalCode":"05679"
       },
       {
          "city":"Santa Fé De Antioquia",
          "postalCode":"05042"
       },
       {
          "city":"Santa Rosa De Osos",
          "postalCode":"05686"
       },
       {
          "city":"Santo Domingo",
          "postalCode":"05690"
       },
       {
          "city":"Segovia",
          "postalCode":"05736"
       },
       {
          "city":"Sonsón",
          "postalCode":"05756"
       },
       {
          "city":"Sopetrán",
          "postalCode":"05761"
       },
       {
          "city":"Támesis",
          "postalCode":"05789"
       },
       {
          "city":"Tarazá",
          "postalCode":"05790"
       },
       {
          "city":"Tarso",
          "postalCode":"05792"
       },
       {
          "city":"Titiribí",
          "postalCode":"05809"
       },
       {
          "city":"Toledo",
          "postalCode":"05819"
       },
       {
          "city":"Turbo",
          "postalCode":"05837"
       },
       {
          "city":"Uramita",
          "postalCode":"05842"
       },
       {
          "city":"Urrao",
          "postalCode":"05847"
       },
       {
          "city":"Valdivia",
          "postalCode":"05854"
       },
       {
          "city":"Valparaíso",
          "postalCode":"05856"
       },
       {
          "city":"Vegachí",
          "postalCode":"05858"
       },
       {
          "city":"Venecia",
          "postalCode":"05861"
       },
       {
          "city":"Vigía Del Fuerte",
          "postalCode":"05873"
       },
       {
          "city":"Yalí",
          "postalCode":"05885"
       },
       {
          "city":"Yarumal",
          "postalCode":"05887"
       },
       {
          "city":"Yolombó",
          "postalCode":"05890"
       },
       {
          "city":"Yondó",
          "postalCode":"05893"
       },
       {
          "city":"Zaragoza",
          "postalCode":"05895"
       },
    ]
 },
 {
    "state":"Arauca",
    "item":[
       {
          "city":"Arauca",
          "postalCode":"81001"
       },
       {
          "city":"Arauquita",
          "postalCode":"81065"
       },
       {
          "city":"Cravo Norte",
          "postalCode":"81220"
       },
       {
          "city":"Fortul",
          "postalCode":"81300"
       },
       {
          "city":"Puerto Rondón",
          "postalCode":"81591"
       },
       {
          "city":"Saravena",
          "postalCode":"81736"
       },
       {
          "city":"Tame",
          "postalCode":"81794"
       }
    ]
 },
 {
    "state":"Atlántico",
    "item":[
       {
          "city":"Baranoa",
          "postalCode":"08078"
       },
       {
          "city":"Barranquilla",
          "postalCode":"08001"
       },
       {
          "city":"Campo De La Cruz",
          "postalCode":"08137"
       },
       {
          "city":"Candelaria",
          "postalCode":"08141"
       },
       {
          "city":"Galapa",
          "postalCode":"08296"
       },
       {
          "city":"Juan De Acosta",
          "postalCode":"08372"
       },
       {
          "city":"Luruaco",
          "postalCode":"08421"
       },
       {
          "city":"Malambo",
          "postalCode":"08433"
       },
       {
          "city":"Manatí",
          "postalCode":"08436"
       },
       {
          "city":"Palmar De Varela",
          "postalCode":"08520"
       },
       {
          "city":"Piojó",
          "postalCode":"08549"
       },
       {
          "city":"Polonuevo",
          "postalCode":"08558"
       },
       {
          "city":"Ponedera",
          "postalCode":"08560"
       },
       {
          "city":"Puerto Colombia",
          "postalCode":"08573"
       },
       {
          "city":"Repelón",
          "postalCode":"08606"
       },
       {
          "city":"Sabanagrande",
          "postalCode":"08634"
       },
       {
          "city":"Sabanalarga",
          "postalCode":"08638"
       },
       {
          "city":"Santa Lucía",
          "postalCode":"08675"
       },
       {
          "city":"Santo Tomás",
          "postalCode":"08685"
       },
       {
          "city":"Soledad",
          "postalCode":"08758"
       },
       {
          "city":"Suan",
          "postalCode":"08770"
       },
       {
          "city":"Tubará",
          "postalCode":"08832"
       },
       {
          "city":"Usiacurí",
          "postalCode":"08849"
       },
    ]
 },
 {
    "state":"Bolívar",
    "item":[
       {
          "city":"Achí",
          "postalCode":"13006"
       },
       {
          "city":"Altos Del Rosario",
          "postalCode":"13030"
       },
       {
          "city":"Arenal",
          "postalCode":"13042"
       },
       {
          "city":"Arjona",
          "postalCode":"13052"
       },
       {
          "city":"Arroyohondo",
          "postalCode":"13062"
       },
       {
          "city":"Barranco De Loba",
          "postalCode":"13074"
       },
       {
          "city":"Calamar",
          "postalCode":"13140"
       },
       {
          "city":"Cantagallo",
          "postalCode":"13160"
       },
       {
          "city":"Cartagena De Indias",
          "postalCode":"13001"
       },
       {
          "city":"Cicuco",
          "postalCode":"13188"
       },
       {
          "city":"Clemencia",
          "postalCode":"13222"
       },
       {
          "city":"Córdoba",
          "postalCode":"13212"
       },
       {
          "city":"El Carmen De Bolívar",
          "postalCode":"13244"
       },
       {
          "city":"El Guamo",
          "postalCode":"13248"
       },
       {
          "city":"El Peñón",
          "postalCode":"13268"
       },
       {
          "city":"Hatillo De Loba",
          "postalCode":"13300"
       },
       {
          "city":"Magangué",
          "postalCode":"13430"
       },
       {
          "city":"Mahates",
          "postalCode":"13433"
       },
       {
          "city":"Margarita",
          "postalCode":"13440"
       },
       {
          "city":"María La Baja",
          "postalCode":"13442"
       },
       {
          "city":"Mompós",
          "postalCode":"13468"
       },
       {
          "city":"Montecristo",
          "postalCode":"13458"
       },
       {
          "city":"Morales",
          "postalCode":"13473"
       },
       {
          "city":"Norosí",
          "postalCode":"13490"
       },
       {
          "city":"Pinillos",
          "postalCode":"13549"
       },
       {
          "city":"Regidor",
          "postalCode":"13580"
       },
       {
          "city":"Río Viejo",
          "postalCode":"13600"
       },
       {
          "city":"San Cristóbal",
          "postalCode":"13620"
       },
       {
          "city":"San Estanislao",
          "postalCode":"13647"
       },
       {
          "city":"San Fernando",
          "postalCode":"13650"
       },
       {
          "city":"San Jacinto",
          "postalCode":"13654"
       },
       {
          "city":"San Jacinto Del Cauca",
          "postalCode":"13655"
       },
       {
          "city":"San Juan Nepomuceno",
          "postalCode":"13657"
       },
       {
          "city":"San Martín De Loba",
          "postalCode":"13667"
       },
       {
          "city":"San Pablo",
          "postalCode":"13670"
       },
       {
          "city":"Santa Catalina",
          "postalCode":"13673"
       },
       {
          "city":"Santa Rosa",
          "postalCode":"13683"
       },
       {
          "city":"Santa Rosa Del Sur",
          "postalCode":"13688"
       },
       {
          "city":"Simití",
          "postalCode":"13744"
       },
       {
          "city":"Soplaviento",
          "postalCode":"13760"
       },
       {
          "city":"Talaigua Nuevo",
          "postalCode":"13780"
       },
       {
          "city":"Tiquisio",
          "postalCode":"13810"
       },
       {
          "city":"Turbaco",
          "postalCode":"13836"
       },
       {
          "city":"Turbaná",
          "postalCode":"13838"
       },
       {
          "city":"Villanueva",
          "postalCode":"13873"
       },
       {
          "city":"Zambrano",
          "postalCode":"13894"
       }
    ]
 },
 {
    "state":"Boyacá",
    "item":[
       {
          "city":"Almeida",
          "postalCode":"15022"
       },
       {
          "city":"Aquitania",
          "postalCode":"15047"
       },
       {
          "city":"Arcabuco",
          "postalCode":"15051"
       },
       {
          "city":"Belén",
          "postalCode":"15087"
       },
       {
          "city":"Berbeo",
          "postalCode":"15090"
       },
       {
          "city":"Betéitiva",
          "postalCode":"15092"
       },
       {
          "city":"Boavita",
          "postalCode":"15097"
       },
       {
          "city":"Boyacá",
          "postalCode":"15104"
       },
       {
          "city":"Briceño",
          "postalCode":"15106"
       },
       {
          "city":"Buenavista",
          "postalCode":"15109"
       },
       {
          "city":"Busbanzá",
          "postalCode":"15114"
       },
       {
          "city":"Caldas",
          "postalCode":"15131"
       },
       {
          "city":"Campohermoso",
          "postalCode":"15135"
       },
       {
          "city":"Cerinza",
          "postalCode":"15162"
       },
       {
          "city":"Chinavita",
          "postalCode":"15172"
       },
       {
          "city":"Chiquinquirá",
          "postalCode":"15176"
       },
       {
          "city":"Chíquiza",
          "postalCode":"15232"
       },
       {
          "city":"Chiscas",
          "postalCode":"15180"
       },
       {
          "city":"Chita",
          "postalCode":"15183"
       },
       {
          "city":"Chitaraque",
          "postalCode":"15185"
       },
       {
          "city":"Chivatá",
          "postalCode":"15187"
       },
       {
          "city":"Chivor",
          "postalCode":"15236"
       },
       {
          "city":"Ciénega",
          "postalCode":"15189"
       },
       {
          "city":"Cómbita",
          "postalCode":"15204"
       },
       {
          "city":"Coper",
          "postalCode":"15212"
       },
       {
          "city":"Corrales",
          "postalCode":"15215"
       },
       {
          "city":"Covarachía",
          "postalCode":"15218"
       },
       {
          "city":"Cubará",
          "postalCode":"15223"
       },
       {
          "city":"Cucaita",
          "postalCode":"15224"
       },
       {
          "city":"Cuítiva",
          "postalCode":"15226"
       },
       {
          "city":"Duitama",
          "postalCode":"15238"
       },
       {
          "city":"El Cocuy",
          "postalCode":"15244"
       },
       {
          "city":"El Espino",
          "postalCode":"15248"
       },
       {
          "city":"Firavitoba",
          "postalCode":"15272"
       },
       {
          "city":"Floresta",
          "postalCode":"15276"
       },
       {
          "city":"Gachantivá",
          "postalCode":"15293"
       },
       {
          "city":"Gámeza",
          "postalCode":"15296"
       },
       {
          "city":"Garagoa",
          "postalCode":"15299"
       },
       {
          "city":"Guacamayas",
          "postalCode":"15317"
       },
       {
          "city":"Guateque",
          "postalCode":"15322"
       },
       {
          "city":"Guayatá",
          "postalCode":"15325"
       },
       {
          "city":"Güicán",
          "postalCode":"15332"
       },
       {
          "city":"Iza",
          "postalCode":"15362"
       },
       {
          "city":"Jenesano",
          "postalCode":"15367"
       },
       {
          "city":"Jericó",
          "postalCode":"15368"
       },
       {
          "city":"La Capilla",
          "postalCode":"15380"
       },
       {
          "city":"La Uvita",
          "postalCode":"15403"
       },
       {
          "city":"La Victoria",
          "postalCode":"15401"
       },
       {
          "city":"Labranzagrande",
          "postalCode":"15377"
       },
       {
          "city":"Macanal",
          "postalCode":"15425"
       },
       {
          "city":"Maripí",
          "postalCode":"15442"
       },
       {
          "city":"Miraflores",
          "postalCode":"15455"
       },
       {
          "city":"Mongua",
          "postalCode":"15464"
       },
       {
          "city":"Monguí",
          "postalCode":"15466"
       },
       {
          "city":"Moniquirá",
          "postalCode":"15469"
       },
       {
          "city":"Motavita",
          "postalCode":"15476"
       },
       {
          "city":"Muzo",
          "postalCode":"15480"
       },
       {
          "city":"Nobsa",
          "postalCode":"15491"
       },
       {
          "city":"Nuevo Colón",
          "postalCode":"15494"
       },
       {
          "city":"Oicatá",
          "postalCode":"15500"
       },
       {
          "city":"Otanche",
          "postalCode":"15507"
       },
       {
          "city":"Pachavita",
          "postalCode":"15511"
       },
       {
          "city":"Páez",
          "postalCode":"15514"
       },
       {
          "city":"Paipa",
          "postalCode":"15516"
       },
       {
          "city":"Pajarito",
          "postalCode":"15518"
       },
       {
          "city":"Panqueba",
          "postalCode":"15522"
       },
       {
          "city":"Pauna",
          "postalCode":"15531"
       },
       {
          "city":"Paya",
          "postalCode":"15533"
       },
       {
          "city":"Paz De Río",
          "postalCode":"15537"
       },
       {
          "city":"Pesca",
          "postalCode":"15542"
       },
       {
          "city":"Pisba",
          "postalCode":"15550"
       },
       {
          "city":"Puerto Boyacá",
          "postalCode":"15572"
       },
       {
          "city":"Quípama",
          "postalCode":"15580"
       },
       {
          "city":"Ramiriquí",
          "postalCode":"15599"
       },
       {
          "city":"Ráquira",
          "postalCode":"15600"
       },
       {
          "city":"Rondón",
          "postalCode":"15621"
       },
       {
          "city":"Saboyá",
          "postalCode":"15632"
       },
       {
          "city":"Sáchica",
          "postalCode":"15638"
       },
       {
          "city":"Samacá",
          "postalCode":"15646"
       },
       {
          "city":"San Eduardo",
          "postalCode":"15660"
       },
       {
          "city":"San José De Pare",
          "postalCode":"15664"
       },
       {
          "city":"San Luis De Gaceno",
          "postalCode":"15667"
       },
       {
          "city":"San Mateo",
          "postalCode":"15673"
       },
       {
          "city":"San Miguel De Sema",
          "postalCode":"15676"
       },
       {
          "city":"San Pablo De Borbur",
          "postalCode":"15681"
       },
       {
          "city":"Santa María",
          "postalCode":"15690"
       },
       {
          "city":"Santa Rosa De Viterbo",
          "postalCode":"15693"
       },
       {
          "city":"Santa Sofía",
          "postalCode":"15696"
       },
       {
          "city":"Santana",
          "postalCode":"15686"
       },
       {
          "city":"Sativanorte",
          "postalCode":"15720"
       },
       {
          "city":"Sativasur",
          "postalCode":"15723"
       },
       {
          "city":"Siachoque",
          "postalCode":"15740"
       },
       {
          "city":"Soatá",
          "postalCode":"15753"
       },
       {
          "city":"Socha",
          "postalCode":"15757"
       },
       {
          "city":"Socotá",
          "postalCode":"15755"
       },
       {
          "city":"Sogamoso",
          "postalCode":"15759"
       },
       {
          "city":"Somondoco",
          "postalCode":"15761"
       },
       {
          "city":"Sora",
          "postalCode":"15762"
       },
       {
          "city":"Soracá",
          "postalCode":"15764"
       },
       {
          "city":"Sotaquirá",
          "postalCode":"15763"
       },
       {
          "city":"Susacón",
          "postalCode":"15774"
       },
       {
          "city":"Sutamarchán",
          "postalCode":"15776"
       },
       {
          "city":"Sutatenza",
          "postalCode":"15778"
       },
       {
          "city":"Tasco",
          "postalCode":"15790"
       },
       {
          "city":"Tenza",
          "postalCode":"15798"
       },
       {
          "city":"Tibaná",
          "postalCode":"15804"
       },
       {
          "city":"Tibasosa",
          "postalCode":"15806"
       },
       {
          "city":"Tinjacá",
          "postalCode":"15808"
       },
       {
          "city":"Tipacoque",
          "postalCode":"15810"
       },
       {
          "city":"Toca",
          "postalCode":"15814"
       },
       {
          "city":"Togüí",
          "postalCode":"15816"
       },
       {
          "city":"Tópaga",
          "postalCode":"15820"
       },
       {
          "city":"Tota",
          "postalCode":"15822"
       },
       {
          "city":"Tunja",
          "postalCode":"15001"
       },
       {
          "city":"Tununguá",
          "postalCode":"15832"
       },
       {
          "city":"Turmequé",
          "postalCode":"15835"
       },
       {
          "city":"Tuta",
          "postalCode":"15837"
       },
       {
          "city":"Tutazá",
          "postalCode":"15839"
       },
       {
          "city":"Úmbita",
          "postalCode":"15842"
       },
       {
          "city":"Ventaquemada",
          "postalCode":"15861"
       },
       {
          "city":"Villa De Leyva",
          "postalCode":"15407"
       },
       {
          "city":"Viracachá",
          "postalCode":"15879"
       },
       {
          "city":"Zetaquira",
          "postalCode":"15897"
       }
    ]
 },
 {
    "state":"Caldas",
    "item":[
       {
          "city":"Aguadas",
          "postalCode":"17013"
       },
       {
          "city":"Anserma",
          "postalCode":"17042"
       },
       {
          "city":"Aranzazu",
          "postalCode":"17050"
       },
       {
          "city":"Belalcázar",
          "postalCode":"17088"
       },
       {
          "city":"Chinchiná",
          "postalCode":"17174"
       },
       {
          "city":"Filadelfia",
          "postalCode":"17272"
       },
       {
          "city":"La Dorada",
          "postalCode":"17380"
       },
       {
          "city":"La Merced",
          "postalCode":"17388"
       },
       {
          "city":"Manizales",
          "postalCode":"17001"
       },
       {
          "city":"Manzanares",
          "postalCode":"17433"
       },
       {
          "city":"Marmato",
          "postalCode":"17442"
       },
       {
          "city":"Marquetalia",
          "postalCode":"17444"
       },
       {
          "city":"Marulanda",
          "postalCode":"17446"
       },
       {
          "city":"Neira",
          "postalCode":"17486"
       },
       {
          "city":"Norcasia",
          "postalCode":"17495"
       },
       {
          "city":"Pácora",
          "postalCode":"17513"
       },
       {
          "city":"Palestina",
          "postalCode":"17524"
       },
       {
          "city":"Pensilvania",
          "postalCode":"17541"
       },
       {
          "city":"Riosucio",
          "postalCode":"17614"
       },
       {
          "city":"Risaralda",
          "postalCode":"17616"
       },
       {
          "city":"Salamina",
          "postalCode":"17653"
       },
       {
          "city":"Samaná",
          "postalCode":"17662"
       },
       {
          "city":"San José",
          "postalCode":"17665"
       },
       {
          "city":"Supía",
          "postalCode":"17777"
       },
       {
          "city":"Victoria",
          "postalCode":"17867"
       },
       {
          "city":"Villamaría",
          "postalCode":"17873"
       },
       {
          "city":"Viterbo",
          "postalCode":"17877"
       }
    ]
 },
 {
    "state":"Caquetá",
    "item":[
       {
          "city":"Albania",
          "postalCode":"18029"
       },
       {
          "city":"Belén De Los Andaquíes",
          "postalCode":"18094"
       },
       {
          "city":"Cartagena Del Chairá",
          "postalCode":"18150"
       },
       {
          "city":"Curillo",
          "postalCode":"18205"
       },
       {
          "city":"El Doncello",
          "postalCode":"18247"
       },
       {
          "city":"El Paujíl",
          "postalCode":"18256"
       },
       {
          "city":"Florencia",
          "postalCode":"18001"
       },
       {
          "city":"La Montañita",
          "postalCode":"18410"
       },
       {
          "city":"Milán",
          "postalCode":"18460"
       },
       {
          "city":"Morelia",
          "postalCode":"18479"
       },
       {
          "city":"Puerto Rico",
          "postalCode":"18592"
       },
       {
          "city":"San José Del Fragua",
          "postalCode":"18610"
       },
       {
          "city":"San Vicente Del Caguán",
          "postalCode":"18753"
       },
       {
          "city":"Solano",
          "postalCode":"18756"
       },
       {
          "city":"Solita",
          "postalCode":"18785"
       },
       {
          "city":"Valparaíso",
          "postalCode":"18860"
       }
    ]
 },
 {
    "state":"Casanare",
    "item":[
       {
          "city":"Aguazul",
          "postalCode":"85010"
       },
       {
          "city":"Chámeza",
          "postalCode":"85015"
       },
       {
          "city":"Hato Corozal",
          "postalCode":"85125"
       },
       {
          "city":"La Salina",
          "postalCode":"85136"
       },
       {
          "city":"Maní",
          "postalCode":"85139"
       },
       {
          "city":"Monterrey",
          "postalCode":"85162"
       },
       {
          "city":"Nunchía",
          "postalCode":"85225"
       },
       {
          "city":"Orocué",
          "postalCode":"85230"
       },
       {
          "city":"Paz De Ariporo",
          "postalCode":"85250"
       },
       {
          "city":"Pore",
          "postalCode":"85263"
       },
       {
          "city":"Recetor",
          "postalCode":"85279"
       },
       {
          "city":"Sabanalarga",
          "postalCode":"85300"
       },
       {
          "city":"Sácama",
          "postalCode":"85315"
       },
       {
          "city":"San Luis De Palenque",
          "postalCode":"85325"
       },
       {
          "city":"Támara",
          "postalCode":"85400"
       },
       {
          "city":"Tauramena",
          "postalCode":"85410"
       },
       {
          "city":"Trinidad",
          "postalCode":"85430"
       },
       {
          "city":"Villanueva",
          "postalCode":"85440"
       },
       {
          "city":"Yopal",
          "postalCode":"85001"
       }
    ]
 },
 {
    "state":"Cauca",
    "item":[
       {
          "city":"Almaguer",
          "postalCode":"19022"
       },
       {
          "city":"Argelia",
          "postalCode":"19050"
       },
       {
          "city":"Balboa",
          "postalCode":"19075"
       },
       {
          "city":"Bolívar",
          "postalCode":"19100"
       },
       {
          "city":"Buenos Aires",
          "postalCode":"19110"
       },
       {
          "city":"Cajibío",
          "postalCode":"19130"
       },
       {
          "city":"Caldono",
          "postalCode":"19137"
       },
       {
          "city":"Caloto",
          "postalCode":"19142"
       },
       {
          "city":"Corinto",
          "postalCode":"19212"
       },
       {
          "city":"El Tambo",
          "postalCode":"19256"
       },
       {
          "city":"Florencia",
          "postalCode":"19290"
       },
       {
          "city":"Guachené",
          "postalCode":"19300"
       },
       {
          "city":"Guapí",
          "postalCode":"19318"
       },
       {
          "city":"Inzá",
          "postalCode":"19355"
       },
       {
          "city":"Jambaló",
          "postalCode":"19364"
       },
       {
          "city":"La Sierra",
          "postalCode":"19392"
       },
       {
          "city":"La Vega",
          "postalCode":"19397"
       },
       {
          "city":"López De Micay",
          "postalCode":"19418"
       },
       {
          "city":"Mercaderes",
          "postalCode":"19450"
       },
       {
          "city":"Miranda",
          "postalCode":"19455"
       },
       {
          "city":"Morales",
          "postalCode":"19473"
       },
       {
          "city":"Padilla",
          "postalCode":"19513"
       },
       {
          "city":"Páez",
          "postalCode":"19517"
       },
       {
          "city":"Patía",
          "postalCode":"19532"
       },
       {
          "city":"Piamonte",
          "postalCode":"19533"
       },
       {
          "city":"Piendamó",
          "postalCode":"19548"
       },
       {
          "city":"Popayán",
          "postalCode":"19001"
       },
       {
          "city":"Puerto Tejada",
          "postalCode":"19573"
       },
       {
          "city":"Puracé",
          "postalCode":"19585"
       },
       {
          "city":"Rosas",
          "postalCode":"19622"
       },
       {
          "city":"San Sebastián",
          "postalCode":"19693"
       },
       {
          "city":"Santa Rosa",
          "postalCode":"19701"
       },
       {
          "city":"Santander De Quilichao",
          "postalCode":"19698"
       },
       {
          "city":"Silvia",
          "postalCode":"19743"
       },
       {
          "city":"Sotara",
          "postalCode":"19760"
       },
       {
          "city":"Suárez",
          "postalCode":"19780"
       },
       {
          "city":"Sucre",
          "postalCode":"19785"
       },
       {
          "city":"Timbío",
          "postalCode":"19807"
       },
       {
          "city":"Timbiquí",
          "postalCode":"19809"
       },
       {
          "city":"Toribío",
          "postalCode":"19821"
       },
       {
          "city":"Totoró",
          "postalCode":"19824"
       },
       {
          "city":"Villa Rica",
          "postalCode":"19845"
       }
    ]
 },
 {
    "state":"Cesar",
    "item":[
       {
          "city":"Aguachica",
          "postalCode":"20011"
       },
       {
          "city":"Agustín Codazzi",
          "postalCode":"20013"
       },
       {
          "city":"Astrea",
          "postalCode":"20032"
       },
       {
          "city":"Becerril",
          "postalCode":"20045"
       },
       {
          "city":"Bosconia",
          "postalCode":"20060"
       },
       {
          "city":"Chimichagua",
          "postalCode":"20175"
       },
       {
          "city":"Chiriguaná",
          "postalCode":"20178"
       },
       {
          "city":"Curumaní",
          "postalCode":"20228"
       },
       {
          "city":"El Copey",
          "postalCode":"20238"
       },
       {
          "city":"El Paso",
          "postalCode":"20250"
       },
       {
          "city":"Gamarra",
          "postalCode":"20295"
       },
       {
          "city":"González",
          "postalCode":"20310"
       },
       {
          "city":"La Gloria",
          "postalCode":"20383"
       },
       {
          "city":"La Jagua De Ibirico",
          "postalCode":"20400"
       },
       {
          "city":"La Loma",
          "postalCode":"20250"
       },
       {
          "city":"La Paz",
          "postalCode":"20621"
       },
       {
          "city":"Manaure Balcón Del Cesar",
          "postalCode":"20443"
       },
       {
          "city":"Pailitas",
          "postalCode":"20517"
       },
       {
          "city":"Pelaya",
          "postalCode":"20550"
       },
       {
          "city":"Pueblo Bello",
          "postalCode":"20570"
       },
       {
          "city":"Río De Oro",
          "postalCode":"20614"
       },
       {
          "city":"San Alberto",
          "postalCode":"20710"
       },
       {
          "city":"San Diego",
          "postalCode":"20750"
       },
       {
          "city":"San Martín",
          "postalCode":"20770"
       },
       {
          "city":"Tamalameque",
          "postalCode":"20787"
       },
       {
          "city":"Valledupar",
          "postalCode":"20001"
       }
    ]
 },
 {
    "state":"Chocó",
    "item":[
       {
          "city":"Acandí",
          "postalCode":"27006"
       },
       {
          "city":"Alto Baudó",
          "postalCode":"27025"
       },
       {
          "city":"Atrato",
          "postalCode":"27050"
       },
       {
          "city":"Bagadó",
          "postalCode":"27073"
       },
       {
          "city":"Bahía Solano",
          "postalCode":"27075"
       },
       {
          "city":"Bajo Baudó",
          "postalCode":"27077"
       },
       {
          "city":"Bojayá",
          "postalCode":"27099"
       },
       {
          "city":"Carmen Del Darién",
          "postalCode":"27150"
       },
       {
          "city":"Cértegui",
          "postalCode":"27160"
       },
       {
          "city":"Condoto",
          "postalCode":"27205"
       },
       {
          "city":"El Cantón Del San Pablo",
          "postalCode":"27135"
       },
       {
          "city":"El Carmen De Atrato",
          "postalCode":"27245"
       },
       {
          "city":"El Litoral Del San Juan",
          "postalCode":"27250"
       },
       {
          "city":"Istmina",
          "postalCode":"27361"
       },
       {
          "city":"Juradó",
          "postalCode":"27372"
       },
       {
          "city":"Lloró",
          "postalCode":"27413"
       },
       {
          "city":"Medio Atrato",
          "postalCode":"27425"
       },
       {
          "city":"Medio Baudó",
          "postalCode":"27430"
       },
       {
          "city":"Medio San Juan",
          "postalCode":"27450"
       },
       {
          "city":"Nóvita",
          "postalCode":"27491"
       },
       {
          "city":"Nuquí",
          "postalCode":"27495"
       },
       {
          "city":"Quibdó",
          "postalCode":"27001"
       },
       {
          "city":"Río Iró",
          "postalCode":"27580"
       },
       {
          "city":"Río Quito",
          "postalCode":"27600"
       },
       {
          "city":"Riosucio",
          "postalCode":"27615"
       },
       {
          "city":"San José Del Palmar",
          "postalCode":"27660"
       },
       {
          "city":"Sipí",
          "postalCode":"27745"
       },
       {
          "city":"Tadó",
          "postalCode":"27787"
       },
       {
          "city":"Unguía",
          "postalCode":"27800"
       },
       {
          "city":"Unión Pastatericana",
          "postalCode":"27810"
       }
    ]
 },
 {
    "state":"Córdoba",
    "item":[
       {
          "city":"Ayapel",
          "postalCode":"23068"
       },
       {
          "city":"Buenavista",
          "postalCode":"23079"
       },
       {
          "city":"Canalete",
          "postalCode":"23090"
       },
       {
          "city":"Cereté",
          "postalCode":"23162"
       },
       {
          "city":"Chimá",
          "postalCode":"23168"
       },
       {
          "city":"Chinú",
          "postalCode":"23182"
       },
       {
          "city":"Ciénaga De Oro",
          "postalCode":"23189"
       },
       {
          "city":"Cotorra",
          "postalCode":"23300"
       },
       {
          "city":"La Apartada",
          "postalCode":"23350"
       },
       {
          "city":"Lorica",
          "postalCode":"23417"
       },
       {
          "city":"Los Córdobas",
          "postalCode":"23419"
       },
       {
          "city":"Momil",
          "postalCode":"23464"
       },
       {
          "city":"Moñitos",
          "postalCode":"23500"
       },
       {
          "city":"Montelíbano",
          "postalCode":"23466"
       },
       {
          "city":"Montería",
          "postalCode":"23001"
       },
       {
          "city":" Planeta Rica",
          "postalCode":"23555"
       },
       {
          "city":" Pueblo Nuevo",
          "postalCode":"23570"
       },
       {
          "city":"Puerto Escondido",
          "postalCode":"23574"
       },
       {
          "city":"Puerto Libertador",
          "postalCode":"23580"
       },
       {
          "city":"Purísima De La Concepción",
          "postalCode":"23586"
       },
       {
          "city":"Sahagún",
          "postalCode":"23660"
       },
       {
          "city":"San Andrés De Sotavento",
          "postalCode":"23670"
       },
       {
          "city":"San Antero",
          "postalCode":"23672"
       },
       {
          "city":"San Bernardo Del Viento",
          "postalCode":"23675"
       },
       {
          "city":"San Carlos",
          "postalCode":"23678"
       },
       {
          "city":"San José De Uré",
          "postalCode":"23682"
       },
       {
          "city":"San Pelayo",
          "postalCode":"23686"
       },
       {
          "city":"Tierralta",
          "postalCode":"23807"
       },
       {
          "city":"Tuchín",
          "postalCode":"23815"
       },
       {
          "city":"Valencia",
          "postalCode":"23855"
       }
    ]
 },
 {
    "state":"Cundinamarca",
    "item":[
       {
          "city":"Agua De Dios",
          "postalCode":"25001"
       },
       {
          "city":"Albán",
          "postalCode":"25019"
       },
       {
          "city":"Anapoima",
          "postalCode":"25035"
       },
       {
          "city":"Anolaima",
          "postalCode":"25040"
       },
       {
          "city":"Apulo",
          "postalCode":"25599"
       },
       {
          "city":"Arbeláez",
          "postalCode":"25053"
       },
       {
          "city":"Beltrán",
          "postalCode":"25086"
       },
       {
          "city":"Bituima",
          "postalCode":"25095"
       },
       {
          "city":"Bojacá",
          "postalCode":"25099"
       },
       {
          "city":"Cabrera",
          "postalCode":"25120"
       },
       {
          "city":"Cachipay",
          "postalCode":"25123"
       },
       {
          "city":"Cajicá",
          "postalCode":"25126"
       },
       {
          "city":"Caparrapí",
          "postalCode":"25148"
       },
       {
          "city":"Cáqueza",
          "postalCode":"25151"
       },
       {
          "city":"Carmen De Carupa",
          "postalCode":"25154"
       },
       {
          "city":"Chaguaní",
          "postalCode":"25168"
       },
       {
          "city":"Chía",
          "postalCode":"25175"
       },
       {
          "city":"Chipaque",
          "postalCode":"25178"
       },
       {
          "city":"Choachí",
          "postalCode":"25181"
       },
       {
          "city":"Chocontá",
          "postalCode":"25183"
       },
       {
          "city":"Cogua",
          "postalCode":"25200"
       },
       {
          "city":"Cota",
          "postalCode":"25214"
       },
       {
          "city":"Cucunubá",
          "postalCode":"25224"
       },
       {
          "city":"El Colegio",
          "postalCode":"25245"
       },
       {
          "city":"El Peñón",
          "postalCode":"25258"
       },
       {
          "city":"El Rosal",
          "postalCode":"25260"
       },
       {
          "city":"Facatativá",
          "postalCode":"25269"
       },
       {
          "city":"Fómeque",
          "postalCode":"25279"
       },
       {
          "city":"Fosca",
          "postalCode":"25281"
       },
       {
          "city":"Funza",
          "postalCode":"25286"
       },
       {
          "city":"Fúquene",
          "postalCode":"25288"
       },
       {
          "city":"Fusagasugá",
          "postalCode":"25290"
       },
       {
          "city":"Gachalá",
          "postalCode":"25293"
       },
       {
          "city":"Gachancipá",
          "postalCode":"25295"
       },
       {
          "city":"Gachetá",
          "postalCode":"25297"
       },
       {
          "city":"Gama",
          "postalCode":"25299"
       },
       {
          "city":"Girardot",
          "postalCode":"25307"
       },
       {
          "city":"Granada",
          "postalCode":"25312"
       },
       {
          "city":"Guachetá",
          "postalCode":"25317"
       },
       {
          "city":"Guaduas",
          "postalCode":"25320"
       },
       {
          "city":"Guasca",
          "postalCode":"25322"
       },
       {
          "city":"Guataquí",
          "postalCode":"25324"
       },
       {
          "city":"Guatavita",
          "postalCode":"25326"
       },
       {
          "city":"Guayabal De Síquima",
          "postalCode":"25328"
       },
       {
          "city":"Guayabetal",
          "postalCode":"25335"
       },
       {
          "city":"Gutiérrez",
          "postalCode":"25339"
       },
       {
          "city":"Jerusalén",
          "postalCode":"25368"
       },
       {
          "city":"Junín",
          "postalCode":"25372"
       },
       {
          "city":"La Calera",
          "postalCode":"25377"
       },
       {
          "city":"La Mesa",
          "postalCode":"25386"
       },
       {
          "city":"La Palma",
          "postalCode":"25394"
       },
       {
          "city":"La Peña",
          "postalCode":"25398"
       },
       {
          "city":"La Vega",
          "postalCode":"25402"
       },
       {
          "city":"Lenguazaque",
          "postalCode":"25407"
       },
       {
          "city":"Machetá",
          "postalCode":"25426"
       },
       {
          "city":"Madrid",
          "postalCode":"25430"
       },
       {
          "city":"Manta",
          "postalCode":"25436"
       },
       {
          "city":"Medina",
          "postalCode":"25438"
       },
       {
          "city":"Mosquera",
          "postalCode":"25473"
       },
       {
          "city":"Nariño",
          "postalCode":"25483"
       },
       {
          "city":"Nemocón",
          "postalCode":"25486"
       },
       {
          "city":"Nilo",
          "postalCode":"25488"
       },
       {
          "city":"Nimaima",
          "postalCode":"25489"
       },
       {
          "city":"Nocaima",
          "postalCode":"25491"
       },
       {
          "city":"Pacho",
          "postalCode":"25513"
       },
       {
          "city":"Paime",
          "postalCode":"25518"
       },
       {
          "city":"Pandi",
          "postalCode":"25524"
       },
       {
          "city":"Paratebueno",
          "postalCode":"25530"
       },
       {
          "city":"Pasca",
          "postalCode":"25535"
       },
       {
          "city":"Puerto Salgar",
          "postalCode":"25572"
       },
       {
          "city":"Pulí",
          "postalCode":"25580"
       },
       {
          "city":"Quebradanegra",
          "postalCode":"25592"
       },
       {
          "city":"Quetame",
          "postalCode":"25594"
       },
       {
          "city":"Quipile",
          "postalCode":"25596"
       },
       {
          "city":"Ricaurte",
          "postalCode":"25612"
       },
       {
          "city":"San Antonio Del Tequendama",
          "postalCode":"25645"
       },
       {
          "city":"San Bernardo",
          "postalCode":"25649"
       },
       {
          "city":"San Cayetano",
          "postalCode":"25653"
       },
       {
          "city":"San Francisco",
          "postalCode":"25658"
       },
       {
          "city":"San Juan De Rioseco",
          "postalCode":"25662"
       },
       {
          "city":"Sasaima",
          "postalCode":"25718"
       },
       {
          "city":"Sesquilé",
          "postalCode":"25736"
       },
       {
          "city":"Sibaté",
          "postalCode":"25740"
       },
       {
          "city":"Silvania",
          "postalCode":"25743"
       },
       {
          "city":"Simijaca",
          "postalCode":"25745"
       },
       {
          "city":"Soacha",
          "postalCode":"25754"
       },
       {
          "city":"Sopó",
          "postalCode":"25758"
       },
       {
          "city":"Subachoque",
          "postalCode":"25769"
       },
       {
          "city":"Suesca",
          "postalCode":"25772"
       },
       {
          "city":"Supatá",
          "postalCode":"25777"
       },
       {
          "city":"Susa",
          "postalCode":"25779"
       },
       {
          "city":"Sutatausa",
          "postalCode":"25781"
       },
       {
          "city":"Tabio",
          "postalCode":"25785"
       },
       {
          "city":"Tausa",
          "postalCode":"25793"
       },
       {
          "city":"Tena",
          "postalCode":"25797"
       },
       {
          "city":"Tenjo",
          "postalCode":"25799"
       },
       {
          "city":"Tibacuy",
          "postalCode":"25805"
       },
       {
          "city":"Tibirita",
          "postalCode":"25807"
       },
       {
          "city":"Tocaima",
          "postalCode":"25815"
       },
       {
          "city":"Tocancipá",
          "postalCode":"25817"
       },
       {
          "city":"Topaipí",
          "postalCode":"25823"
       },
       {
          "city":"Ubalá",
          "postalCode":"25839"
       },
       {
          "city":"Ubaque",
          "postalCode":"25841"
       },
       {
          "city":"Une",
          "postalCode":"25845"
       },
       {
          "city":"Útica",
          "postalCode":"25851"
       },
       {
          "city":"Venecia",
          "postalCode":"25506"
       },
       {
          "city":"Vergara",
          "postalCode":"25862"
       },
       {
          "city":"Vianí",
          "postalCode":"25867"
       },
       {
          "city":"Villa De San Diego De Ubaté",
          "postalCode":"25843"
       },
       {
          "city":"Villagómez",
          "postalCode":"25871"
       },
       {
          "city":"Villapinzón",
          "postalCode":"25873"
       },
       {
          "city":"Villeta",
          "postalCode":"25875"
       },
       {
          "city":"Viotá",
          "postalCode":"25878"
       },
       {
          "city":"Yacopí",
          "postalCode":"25885"
       },
       {
          "city":"Zipacón",
          "postalCode":"25898"
       },
       {
          "city":"Zipaquirá",
          "postalCode":"25899"
       }
    ]
 },
 {
    "state":"Guainía",
    "item":[
       {
          "city":"Barranco Minas",
          "postalCode":"94343"
       },
       {
          "city":"Cacahual",
          "postalCode":"94886"
       },
       {
          "city":"Inírida",
          "postalCode":"94001"
       },
       {
          "city":"La Guadalupe",
          "postalCode":"94885"
       },
       {
          "city":"Mapiripana",
          "postalCode":"94663"
       },
       {
          "city":"Morichal",
          "postalCode":"94888"
       },
       {
          "city":"Pana Pana",
          "postalCode":"94887"
       },
       {
          "city":"Puerto Colombia",
          "postalCode":"94884"
       },
       {
          "city":"San Felipe",
          "postalCode":"94883"
       }
    ]
 },
 {
    "state":"Guaviare",
    "item":[
       {
          "city":"Calamar",
          "postalCode":"95015"
       },
       {
          "city":"El Retorno",
          "postalCode":"95025"
       },
       {
          "city":"Miraflores",
          "postalCode":"95200"
       },
       {
          "city":"San José Del Guaviare",
          "postalCode":"95001"
       }
    ]
 },
 {
    "state":"Huila",
    "item":[
       {
          "city":"Acevedo",
          "postalCode":"41006"
       },
       {
          "city":"Agrado",
          "postalCode":"41013"
       },
       {
          "city":"Aipe",
          "postalCode":"41016"
       },
       {
          "city":"Algeciras",
          "postalCode":"41020"
       },
       {
          "city":"Altamira",
          "postalCode":"41026"
       },
       {
          "city":"Baraya",
          "postalCode":"41078"
       },
       {
          "city":"Campoalegre",
          "postalCode":"41132"
       },
       {
          "city":"Colombia",
          "postalCode":"41206"
       },
       {
          "city":"Elías",
          "postalCode":"41244"
       },
       {
          "city":"Garzón",
          "postalCode":"41298"
       },
       {
          "city":"Gigante",
          "postalCode":"41306"
       },
       {
          "city":"Guadalupe",
          "postalCode":"41319"
       },
       {
          "city":"Hobo",
          "postalCode":"41349"
       },
       {
          "city":"Íquira",
          "postalCode":"41357"
       },
       {
          "city":"Isnos",
          "postalCode":"41359"
       },
       {
          "city":"La Argentina",
          "postalCode":"41378"
       },
       {
          "city":" La Plata",
          "postalCode":"41396"
       },
       {
          "city":"Nátaga",
          "postalCode":"41483"
       },
       {
          "city":"Neiva",
          "postalCode":"41001"
       },
       {
          "city":"Oporapa",
          "postalCode":"41503"
       },
       {
          "city":"Paicol",
          "postalCode":"41518"
       },
       {
          "city":"Palermo",
          "postalCode":"41524"
       },
       {
          "city":"Palestina",
          "postalCode":"41530"
       },
       {
          "city":"Pital",
          "postalCode":"41548"
       },
       {
          "city":"Pitalito",
          "postalCode":"41551"
       },
       {
          "city":"Rivera",
          "postalCode":"41615"
       },
       {
          "city":"Saladoblanco",
          "postalCode":"41660"
       },
       {
          "city":"San Agustín",
          "postalCode":"41668"
       },
       {
          "city":"Santa María",
          "postalCode":"41676"
       },
       {
          "city":"Suaza",
          "postalCode":"41770"
       },
       {
          "city":"Tarqui",
          "postalCode":"41791"
       },
       {
          "city":"Tello",
          "postalCode":"41799"
       },
       {
          "city":"Teruel",
          "postalCode":"41801"
       },
       {
          "city":"Tesalia",
          "postalCode":"41797"
       },
       {
          "city":"Timaná",
          "postalCode":"41807"
       },
       {
          "city":"Villavieja",
          "postalCode":"41872"
       },
       {
          "city":"Yaguará",
          "postalCode":"41885"
       }
    ]
 },
 {
    "state":"La Guajira",
    "item":[
       {
          "city":"Albania",
          "postalCode":"44035"
       },
       {
          "city":"Barrancas",
          "postalCode":"44078"
       },
       {
          "city":"Dibulla",
          "postalCode":"44090"
       },
       {
          "city":"Distracción",
          "postalCode":"44098"
       },
       {
          "city":"El Molino",
          "postalCode":"44110"
       },
       {
          "city":"Fonseca",
          "postalCode":"44279"
       },
       {
          "city":"Hatonuevo",
          "postalCode":"44378"
       },
       {
          "city":"La Jagua Del Pilar",
          "postalCode":"44420"
       },
       {
          "city":"Maicao",
          "postalCode":"44430"
       },
       {
          "city":"Manaure",
          "postalCode":"44560"
       },
       {
          "city":"Riohacha",
          "postalCode":"44001"
       },
       {
          "city":"San Juan Del Cesar",
          "postalCode":"44650"
       },
       {
          "city":"Uribia",
          "postalCode":"44847"
       },
       {
          "city":"Urumita",
          "postalCode":"44855"
       },
       {
          "city":"Villanueva",
          "postalCode":"44874"
       }
    ]
 },
 {
    "state":"Magdalena",
    "item":[
       {
          "city":"Algarrobo",
          "postalCode":"47030"
       },
       {
          "city":"Aracataca",
          "postalCode":"47053"
       },
       {
          "city":"Ariguaní",
          "postalCode":"47058"
       },
       {
          "city":"Cerro De San Antonio",
          "postalCode":"47161"
       },
       {
          "city":"Chivolo",
          "postalCode":"47170"
       },
       {
          "city":"Ciénaga",
          "postalCode":"47189"
       },
       {
          "city":"Concordia",
          "postalCode":"47205"
       },
       {
          "city":"El Banco",
          "postalCode":"47245"
       },
       {
          "city":"El Piñón",
          "postalCode":"47258"
       },
       {
          "city":"El Retén",
          "postalCode":"47268"
       },
       {
          "city":"Fundación",
          "postalCode":"47288"
       },
       {
          "city":"Guamal",
          "postalCode":"47318"
       },
       {
          "city":"Nueva Granada",
          "postalCode":"47460"
       },
       {
          "city":"Pedraza",
          "postalCode":"47541"
       },
       {
          "city":"Pijiño Del Carmen",
          "postalCode":"47545"
       },
       {
          "city":"Pivijay",
          "postalCode":"47551"
       },
       {
          "city":"Plato",
          "postalCode":"47555"
       },
       {
          "city":"Puebloviejo",
          "postalCode":"47570"
       },
       {
          "city":"Remolino",
          "postalCode":"47605"
       },
       {
          "city":"Sabanas De San Ángel",
          "postalCode":"47660"
       },
       {
          "city":"Salamina",
          "postalCode":"47675"
       },
       {
          "city":"San Sebastián De Buenavista",
          "postalCode":"47692"
       },
       {
          "city":"San Zenón",
          "postalCode":"47703"
       },
       {
          "city":"Santa Ana",
          "postalCode":"47707"
       },
       {
          "city":"Santa Bárbara De Pinto",
          "postalCode":"47720"
       },
       {
          "city":"Santa Marta",
          "postalCode":"47001"
       },
       {
          "city":"Sitionuevo",
          "postalCode":"47745"
       },
       {
          "city":"Tenerife",
          "postalCode":"47798"
       },
       {
          "city":"Zapayán",
          "postalCode":"47960"
       },
       {
          "city":"Zona Bananera",
          "postalCode":"47980"
       }
    ]
 },
 {
    "state":"Meta",
    "item":[
       {
          "city":"Acacías",
          "postalCode":"50006"
       },
       {
          "city":"Barranca De Upía",
          "postalCode":"50110"
       },
       {
          "city":"Cabuyaro",
          "postalCode":"50124"
       },
       {
          "city":"Castilla La Nueva",
          "postalCode":"50150"
       },
       {
          "city":"Cumaral",
          "postalCode":"50226"
       },
       {
          "city":"El Calvario",
          "postalCode":"50245"
       },
       {
          "city":"El Castillo",
          "postalCode":"50251"
       },
       {
          "city":"El Dorado",
          "postalCode":"50270"
       },
       {
          "city":"Fuente De Oro",
          "postalCode":"50287"
       },
       {
          "city":"Granada",
          "postalCode":"50313"
       },
       {
          "city":"Guamal",
          "postalCode":"50318"
       },
       {
          "city":"La Macarena",
          "postalCode":"50350"
       },
       {
          "city":"Lejanías",
          "postalCode":"50400"
       },
       {
          "city":"Mapiripán",
          "postalCode":"50325"
       },
       {
          "city":"Mesetas",
          "postalCode":"50330"
       },
       {
          "city":"Puerto Concordia",
          "postalCode":"50450"
       },
       {
          "city":"Puerto Gaitán",
          "postalCode":"50568"
       },
       {
          "city":"Puerto Lleras",
          "postalCode":"50577"
       },
       {
          "city":"Puerto López",
          "postalCode":"50573"
       },
       {
          "city":"Puerto Rico",
          "postalCode":"50590"
       },
       {
          "city":"Restrepo",
          "postalCode":"50606"
       },
       {
          "city":"San Carlos De Guaroa",
          "postalCode":"50680"
       },
       {
          "city":"San Juan De Arama",
          "postalCode":"50683"
       },
       {
          "city":"San Juanito",
          "postalCode":"50686"
       },
       {
          "city":"San Luis De Cubarral",
          "postalCode":"50223"
       },
       {
          "city":"San Martín",
          "postalCode":"50689"
       },
       {
          "city":"Uribe",
          "postalCode":"50370"
       },
       {
          "city":"Villavicencio",
          "postalCode":"50001"
       },
       {
          "city":"Vistahermosa",
          "postalCode":"50711"
       }
    ]
 },
 {
    "state":"Nariño",
    "item":[
       {
          "city":"Albán",
          "postalCode":"52019"
       },
       {
          "city":"Aldana",
          "postalCode":"52022"
       },
       {
          "city":"Ancuyá",
          "postalCode":"52036"
       },
       {
          "city":"Arboleda",
          "postalCode":"52051"
       },
       {
          "city":"Barbacoas",
          "postalCode":"52079"
       },
       {
          "city":"Belén",
          "postalCode":"52083"
       },
       {
          "city":"Buesaco",
          "postalCode":"52110"
       },
       {
          "city":"Chachagüí",
          "postalCode":"52240"
       },
       {
          "city":"Colón",
          "postalCode":"52203"
       },
       {
          "city":"Consacá",
          "postalCode":"52207"
       },
       {
          "city":"Contadero",
          "postalCode":"52210"
       },
       {
          "city":"Córdoba",
          "postalCode":"52215"
       },
       {
          "city":"Cuaspúd",
          "postalCode":"52224"
       },
       {
          "city":"Cumbal",
          "postalCode":"52227"
       },
       {
          "city":"Cumbitara",
          "postalCode":"52233"
       },
       {
          "city":"El Charco",
          "postalCode":"52250"
       },
       {
          "city":"El Peñol",
          "postalCode":"52254"
       },
       {
          "city":"El Rosario",
          "postalCode":"52256"
       },
       {
          "city":"El Tablón De Gómez",
          "postalCode":"52258"
       },
       {
          "city":"El Tambo",
          "postalCode":"52260"
       },
       {
          "city":"Francisco Pizarro",
          "postalCode":"52520"
       },
       {
          "city":"Funes",
          "postalCode":"52287"
       },
       {
          "city":"Guachucal",
          "postalCode":"52317"
       },
       {
          "city":"Guaitarilla",
          "postalCode":"52320"
       },
       {
          "city":"Gualmatán",
          "postalCode":"52323"
       },
       {
          "city":"Iles",
          "postalCode":"52352"
       },
       {
          "city":"Imués",
          "postalCode":"52354"
       },
       {
          "city":"Ipiales",
          "postalCode":"52356"
       },
       {
          "city":"La Cruz",
          "postalCode":"52378"
       },
       {
          "city":"La Florida",
          "postalCode":"52381"
       },
       {
          "city":"La Llanada",
          "postalCode":"52385"
       },
       {
          "city":"La Tola",
          "postalCode":"52390"
       },
       {
          "city":"La Unión",
          "postalCode":"52399"
       },
       {
          "city":"Leiva",
          "postalCode":"52405"
       },
       {
          "city":"Linares",
          "postalCode":"52411"
       },
       {
          "city":"Los Andes",
          "postalCode":"52418"
       },
       {
          "city":"Magüí",
          "postalCode":"52427"
       },
       {
          "city":"Mallama",
          "postalCode":"52435"
       },
       {
          "city":"Mosquera",
          "postalCode":"52473"
       },
       {
          "city":"Nariño",
          "postalCode":"52480"
       },
       {
          "city":"Olaya Herrera",
          "postalCode":"52490"
       },
       {
          "city":"Ospina",
          "postalCode":"52506"
       },
       {
          "city":"Pasto",
          "postalCode":"52001"
       },
       {
          "city":"Policarpa",
          "postalCode":"52540"
       },
       {
          "city":"Potosí",
          "postalCode":"52560"
       },
       {
          "city":"Providencia",
          "postalCode":"52565"
       },
       {
          "city":"Puerres",
          "postalCode":"52573"
       },
       {
          "city":"Pupiales",
          "postalCode":"52585"
       },
       {
          "city":"Ricaurte",
          "postalCode":"52612"
       },
       {
          "city":"Roberto Payán",
          "postalCode":"52621"
       },
       {
          "city":"Samaniego",
          "postalCode":"52678"
       },
       {
          "city":"San Andrés De Tumaco",
          "postalCode":"52835"
       },
       {
          "city":"San Bernardo",
          "postalCode":"52685"
       },
       {
          "city":"San Lorenzo",
          "postalCode":"52687"
       },
       {
          "city":" San Pablo",
          "postalCode":"52693"
       },
       {
          "city":"San Pedro De Cartago",
          "postalCode":"52694"
       },
       {
          "city":"Sandoná",
          "postalCode":"52683"
       },
       {
          "city":"Santa Bárbara",
          "postalCode":"52696"
       },
       {
          "city":"Santacruz",
          "postalCode":"52699"
       },
       {
          "city":"Sapuyes",
          "postalCode":"52720"
       },
       {
          "city":"Taminango",
          "postalCode":"52786"
       },
       {
          "city":"Tangua",
          "postalCode":"52788"
       },
       {
          "city":"Túquerres",
          "postalCode":"52838"
       },
       {
          "city":"Yacuanquer",
          "postalCode":"52885"
       }
    ]
 },
 {
    "state":"Norte De Santander",
    "item":[
       {
          "city":"Ábrego",
          "postalCode":"54003"
       },
       {
          "city":"Arboledas",
          "postalCode":"54051"
       },
       {
          "city":"Bochalema",
          "postalCode":"54099"
       },
       {
          "city":"Bucarasica",
          "postalCode":"54109"
       },
       {
          "city":"Cáchira",
          "postalCode":"54128"
       },
       {
          "city":"Cácota",
          "postalCode":"54125"
       },
       {
          "city":"Chinácota",
          "postalCode":"54172"
       },
       {
          "city":"Chitagá",
          "postalCode":"54174"
       },
       {
          "city":"Convención",
          "postalCode":"54206"
       },
       {
          "city":"Cúcuta",
          "postalCode":"54001"
       },
       {
          "city":"Cucutilla",
          "postalCode":"54223"
       },
       {
          "city":"Durania",
          "postalCode":"54239"
       },
       {
          "city":"El Carmen",
          "postalCode":"54245"
       },
       {
          "city":"El Tarra",
          "postalCode":"54250"
       },
       {
          "city":"El Zulia",
          "postalCode":"54261"
       },
       {
          "city":"Gramalote",
          "postalCode":"54313"
       },
       {
          "city":"Hacarí",
          "postalCode":"54344"
       },
       {
          "city":"Herrán",
          "postalCode":"54347"
       },
       {
          "city":"La Esperanza",
          "postalCode":"54385"
       },
       {
          "city":"La Playa",
          "postalCode":"54398"
       },
       {
          "city":"Labateca",
          "postalCode":"54377"
       },
       {
          "city":"Los Patios",
          "postalCode":"54405"
       },
       {
          "city":"Lourdes",
          "postalCode":"54418"
       },
       {
          "city":"Mutiscua",
          "postalCode":"54480"
       },
       {
          "city":"Ocaña",
          "postalCode":"54498"
       },
       {
          "city":"Pamplona",
          "postalCode":"54518"
       },
       {
          "city":"Pamplonita",
          "postalCode":"54520"
       },
       {
          "city":"Puerto Santander",
          "postalCode":"54553"
       },
       {
          "city":"Ragonvalia",
          "postalCode":"54599"
       },
       {
          "city":"Salazar",
          "postalCode":"54660"
       },
       {
          "city":"San Calixto",
          "postalCode":"54670"
       },
       {
          "city":"San Cayetano",
          "postalCode":"54673"
       },
       {
          "city":"Santiago",
          "postalCode":"54680"
       },
       {
          "city":"Sardinata",
          "postalCode":"54720"
       },
       {
          "city":"Silos",
          "postalCode":"54743"
       },
       {
          "city":"Teorama",
          "postalCode":"54800"
       },
       {
          "city":"Tibú",
          "postalCode":"54810"
       },
       {
          "city":"Toledo",
          "postalCode":"54820"
       },
       {
          "city":"Villa Caro",
          "postalCode":"54871"
       },
       {
          "city":"Villa Del Rosario",
          "postalCode":"54874"
       }
    ]
 },
 {
    "state":"Putumayo",
    "item":[
       {
          "city":"Colón",
          "postalCode":"86219"
       },
       {
          "city":"Mocoa",
          "postalCode":"86001"
       },
       {
          "city":"Orito",
          "postalCode":"86320"
       },
       {
          "city":"Puerto Asís",
          "postalCode":"86568"
       },
       {
          "city":"Puerto Caicedo",
          "postalCode":"86569"
       },
       {
          "city":"Puerto Guzmán",
          "postalCode":"86571"
       },
       {
          "city":"Puerto Leguízamo",
          "postalCode":"86573"
       },
       {
          "city":"San Francisco",
          "postalCode":"86755"
       },
       {
          "city":"San Miguel",
          "postalCode":"86757"
       },
       {
          "city":"Santiago",
          "postalCode":"86760"
       },
       {
          "city":"Sibundoy",
          "postalCode":"86749"
       },
       {
          "city":"Valle Del Guamuez",
          "postalCode":"86865"
       },
       {
          "city":"Villagarzón",
          "postalCode":"86885"
       }
    ]
 },
 {
    "state":"Quindio",
    "item":[
       {
          "city":"Armenia",
          "postalCode":"63001"
       },
       {
          "city":"Buenavista",
          "postalCode":"63111"
       },
       {
          "city":"Calarcá",
          "postalCode":"63130"
       },
       {
          "city":"Circasia",
          "postalCode":"63190"
       },
       {
          "city":"Córdoba",
          "postalCode":"63212"
       },
       {
          "city":"Filandia",
          "postalCode":"63272"
       },
       {
          "city":"Génova",
          "postalCode":"63302"
       },
       {
          "city":"La Tebaida",
          "postalCode":"63401"
       },
       {
          "city":"Montenegro",
          "postalCode":"63470"
       },
       {
          "city":"Pijao",
          "postalCode":"63548"
       },
       {
          "city":"Quimbaya",
          "postalCode":"63594"
       },
       {
          "city":"Salento",
          "postalCode":"63690"
       }
    ]
 },
 {
    "state":"Risaralda",
    "item":[
       {
          "city":"Apía",
          "postalCode":"66045"
       },
       {
          "city":"Balboa",
          "postalCode":"66075"
       },
       {
          "city":" Belén De Umbría",
          "postalCode":"66088"
       },
       {
          "city":"Dosquebradas",
          "postalCode":"66170"
       },
       {
          "city":"Guática",
          "postalCode":"66318"
       },
       {
          "city":"La Celia",
          "postalCode":"66383"
       },
       {
          "city":"La Virginia",
          "postalCode":"66400"
       },
       {
          "city":"Marsella",
          "postalCode":"66440"
       },
       {
          "city":"Mistrató",
          "postalCode":"66456"
       },
       {
          "city":"Pereira",
          "postalCode":"66001"
       },
       {
          "city":"Pueblo Rico",
          "postalCode":"66572"
       },
       {
          "city":"Quinchía",
          "postalCode":"66594"
       },
       {
          "city":"Santa Rosa De Cabal",
          "postalCode":"66682"
       },
       {
          "city":"Santuario",
          "postalCode":"66687"
       }
    ]
 },
 {
    "state":"San Andrés, Providencia Y Santa Catalina",
    "item":[
       {
          "city":"Providencia",
          "postalCode":"88564"
       },
       {
          "city":"San Andrés",
          "postalCode":"88001"
       }
    ]
 },
 {
    "state":"Santander",
    "item":[
       {
          "city":"Aguada",
          "postalCode":"68013"
       },
       {
          "city":"Albania",
          "postalCode":"68020"
       },
       {
          "city":"Aratoca",
          "postalCode":"68051"
       },
       {
          "city":"Barbosa",
          "postalCode":"68077"
       },
       {
          "city":"Barichara",
          "postalCode":"68079"
       },
       {
          "city":"Barrancabermeja",
          "postalCode":"68081"
       },
       {
          "city":"Betulia",
          "postalCode":"68092"
       },
       {
          "city":"Bolívar",
          "postalCode":"68101"
       },
       {
          "city":"Bucaramanga",
          "postalCode":"68001"
       },
       {
          "city":"Cabrera",
          "postalCode":"68121"
       },
       {
          "city":"California",
          "postalCode":"68132"
       },
       {
          "city":"Capitanejo",
          "postalCode":"68147"
       },
       {
          "city":"Carcasí",
          "postalCode":"68152"
       },
       {
          "city":"Cepitá",
          "postalCode":"68160"
       },
       {
          "city":"Cerrito",
          "postalCode":"68162"
       },
       {
          "city":"Charalá",
          "postalCode":"68167"
       },
       {
          "city":"Charta",
          "postalCode":"68169"
       },
       {
          "city":"Chima",
          "postalCode":"68176"
       },
       {
          "city":"Chipatá",
          "postalCode":"68179"
       },
       {
          "city":"Cimitarra",
          "postalCode":"68190"
       },
       {
          "city":"Concepción",
          "postalCode":"68207"
       },
       {
          "city":"Confines",
          "postalCode":"68209"
       },
       {
          "city":"Contratación",
          "postalCode":"68211"
       },
       {
          "city":"Coromoro",
          "postalCode":"68217"
       },
       {
          "city":"Curití",
          "postalCode":"68229"
       },
       {
          "city":"El Carmen De Chucurí",
          "postalCode":"68235"
       },
       {
          "city":"El Guacamayo",
          "postalCode":"68245"
       },
       {
          "city":"El Peñón",
          "postalCode":"68250"
       },
       {
          "city":"El Playón",
          "postalCode":"68255"
       },
       {
          "city":"Encino",
          "postalCode":"68264"
       },
       {
          "city":"Enciso",
          "postalCode":"68266"
       },
       {
          "city":"Florián",
          "postalCode":"68271"
       },
       {
          "city":"Floridablanca",
          "postalCode":"68276"
       },
       {
          "city":"Galán",
          "postalCode":"68296"
       },
       {
          "city":"Gámbita",
          "postalCode":"68298"
       },
       {
          "city":"Girón",
          "postalCode":"68307"
       },
       {
          "city":"Guaca",
          "postalCode":"68318"
       },
       {
          "city":"Guadalupe",
          "postalCode":"68320"
       },
       {
          "city":"Guapotá",
          "postalCode":"68322"
       },
       {
          "city":"Guavatá",
          "postalCode":"68324"
       },
       {
          "city":"Güepsa",
          "postalCode":"68327"
       },
       {
          "city":"Hato",
          "postalCode":"68344"
       },
       {
          "city":"Jesús María",
          "postalCode":"68368"
       },
       {
          "city":"Jordán",
          "postalCode":"68370"
       },
       {
          "city":"La Belleza",
          "postalCode":"68377"
       },
       {
          "city":"La Paz",
          "postalCode":"68397"
       },
       {
          "city":"Landázuri",
          "postalCode":"68385"
       },
       {
          "city":"Lebrija",
          "postalCode":"68406"
       },
       {
          "city":"Los Santos",
          "postalCode":"68418"
       },
       {
          "city":"Macaravita",
          "postalCode":"68425"
       },
       {
          "city":"Málaga",
          "postalCode":"68432"
       },
       {
          "city":"Matanza",
          "postalCode":"68444"
       },
       {
          "city":"Mogotes",
          "postalCode":"68464"
       },
       {
          "city":"Molagavita",
          "postalCode":"68468"
       },
       {
          "city":"Ocamonte",
          "postalCode":"68498"
       },
       {
          "city":"Oiba",
          "postalCode":"68500"
       },
       {
          "city":"Onzaga",
          "postalCode":"68502"
       },
       {
          "city":"Palmar",
          "postalCode":"68522"
       },
       {
          "city":"Palmas Del Socorro",
          "postalCode":"68524"
       },
       {
          "city":"Páramo",
          "postalCode":"68533"
       },
       {
          "city":"Piedecuesta",
          "postalCode":"68547"
       },
       {
          "city":"Pinchote",
          "postalCode":"68549"
       },
       {
          "city":"Puente Nacional",
          "postalCode":"68572"
       },
       {
          "city":"Puerto Parra",
          "postalCode":"68573"
       },
       {
          "city":"Puerto Wilches",
          "postalCode":"68575"
       },
       {
          "city":"Rionegro",
          "postalCode":"68615"
       },
       {
          "city":"Sabana De Torres",
          "postalCode":"68655"
       },
       {
          "city":"San Andrés",
          "postalCode":"68669"
       },
       {
          "city":"San Benito",
          "postalCode":"68673"
       },
       {
          "city":"San Gil",
          "postalCode":"68679"
       },
       {
          "city":"San Joaquín",
          "postalCode":"68682"
       },
       {
          "city":"San José De Miranda",
          "postalCode":"68684"
       },
       {
          "city":"San Miguel",
          "postalCode":"68686"
       },
       {
          "city":"San Vicente De Chucurí",
          "postalCode":"68689"
       },
       {
          "city":"Santa Bárbara",
          "postalCode":"68705"
       },
       {
          "city":"Santa Helena Del Opón",
          "postalCode":"68720"
       },
       {
          "city":"Simacota",
          "postalCode":"68745"
       },
       {
          "city":"Socorro",
          "postalCode":"68755"
       },
       {
          "city":"Suaita",
          "postalCode":"68770"
       },
       {
          "city":"Sucre",
          "postalCode":"68773"
       },
       {
          "city":"Suratá",
          "postalCode":"68780"
       },
       {
          "city":"Tona",
          "postalCode":"68820"
       },
       {
          "city":"Valle De San José",
          "postalCode":"68855"
       },
       {
          "city":"Vélez",
          "postalCode":"68861"
       },
       {
          "city":"Vetas",
          "postalCode":"68867"
       },
       {
          "city":"Villanueva",
          "postalCode":"68872"
       },
       {
          "city":"Zapatoca",
          "postalCode":"68895"
       }
    ]
 },
 {
    "state":"Sucre",
    "item":[
       {
          "city":"Buenavista",
          "postalCode":"70110"
       },
       {
          "city":"Caimito",
          "postalCode":"70124"
       },
       {
          "city":"Chalán",
          "postalCode":"70230"
       },
       {
          "city":"Coloso",
          "postalCode":"70204"
       },
       {
          "city":"Corozal",
          "postalCode":"70215"
       },
       {
          "city":"Coveñas",
          "postalCode":"70221"
       },
       {
          "city":"El Roble",
          "postalCode":"70233"
       },
       {
          "city":"Galeras",
          "postalCode":"70235"
       },
       {
          "city":"Guaranda",
          "postalCode":"70265"
       },
       {
          "city":"La Unión",
          "postalCode":"70400"
       },
       {
          "city":"Los Palmitos",
          "postalCode":"70418"
       },
       {
          "city":"Majagual",
          "postalCode":"70429"
       },
       {
          "city":"Morroa",
          "postalCode":"70473"
       },
       {
          "city":"Ovejas",
          "postalCode":"70508"
       },
       {
          "city":"Palmito",
          "postalCode":"70523"
       },
       {
          "city":"Sampués",
          "postalCode":"70670"
       },
       {
          "city":"San Benito Abad",
          "postalCode":"70678"
       },
       {
          "city":"San Juan De Betulia",
          "postalCode":"70702"
       },
       {
          "city":"San Luis De Sincé",
          "postalCode":"70742"
       },
       {
          "city":"San Marcos",
          "postalCode":"70708"
       },
       {
          "city":"San Onofre",
          "postalCode":"70713"
       },
       {
          "city":"San Pedro",
          "postalCode":"70717"
       },
       {
          "city":"Santiago De Tolú",
          "postalCode":"70820"
       },
       {
          "city":"Sincelejo",
          "postalCode":"70001"
       },
       {
          "city":"Sucre",
          "postalCode":"70771"
       },
       {
          "city":"Tolú Viejo",
          "postalCode":"70823"
       }
    ]
 },
 {
    "state":"Tolima",
    "item":[
       {
          "city":"Alpujarra",
          "postalCode":"73024"
       },
       {
          "city":"Alvarado",
          "postalCode":"73026"
       },
       {
          "city":"Ambalema",
          "postalCode":"73030"
       },
       {
          "city":"Anzoátegui",
          "postalCode":"73043"
       },
       {
          "city":"Armero Guayabal",
          "postalCode":"73055"
       },
       {
          "city":"Ataco",
          "postalCode":"73067"
       },
       {
          "city":"Cajamarca",
          "postalCode":"73124"
       },
       {
          "city":"Carmen De Apicalá",
          "postalCode":"73148"
       },
       {
          "city":"Casabianca",
          "postalCode":"73152"
       },
       {
          "city":"Chaparral",
          "postalCode":"73168"
       },
       {
          "city":"Coello",
          "postalCode":"73200"
       },
       {
          "city":"Coyaima",
          "postalCode":"73217"
       },
       {
          "city":"Cunday",
          "postalCode":"73226"
       },
       {
          "city":"Dolores",
          "postalCode":"73236"
       },
       {
          "city":"Espinal",
          "postalCode":"73268"
       },
       {
          "city":"Falan",
          "postalCode":"73270"
       },
       {
          "city":"Flandes",
          "postalCode":"73275"
       },
       {
          "city":"Fresno",
          "postalCode":"73283"
       },
       {
          "city":"Guamo",
          "postalCode":"73319"
       },
       {
          "city":"Herveo",
          "postalCode":"73347"
       },
       {
          "city":"Honda",
          "postalCode":"73349"
       },
       {
          "city":"Ibagué",
          "postalCode":"73001"
       },
       {
          "city":"Icononzo",
          "postalCode":"73352"
       },
       {
          "city":"Lérida",
          "postalCode":"73408"
       },
       {
          "city":"Líbano",
          "postalCode":"73411"
       },
       {
          "city":"Melgar",
          "postalCode":"73449"
       },
       {
          "city":"Murillo",
          "postalCode":"73461"
       },
       {
          "city":"Natagaima",
          "postalCode":"73483"
       },
       {
          "city":"Ortega",
          "postalCode":"73504"
       },
       {
          "city":"Palocabildo",
          "postalCode":"73520"
       },
       {
          "city":"Piedras",
          "postalCode":"73547"
       },
       {
          "city":"Planadas",
          "postalCode":"73555"
       },
       {
          "city":"Prado",
          "postalCode":"73563"
       },
       {
          "city":"Purificación",
          "postalCode":"73585"
       },
       {
          "city":"Rioblanco",
          "postalCode":"73616"
       },
       {
          "city":"Roncesvalles",
          "postalCode":"73622"
       },
       {
          "city":"Rovira",
          "postalCode":"73624"
       },
       {
          "city":"Saldaña",
          "postalCode":"73671"
       },
       {
          "city":"San Antonio",
          "postalCode":"73675"
       },
       {
          "city":"San Luis",
          "postalCode":"73678"
       },
       {
          "city":"San Sebastián De Mariquita",
          "postalCode":"73443"
       },
       {
          "city":"Santa Isabel",
          "postalCode":"73686"
       },
       {
          "city":"Suárez",
          "postalCode":"73770"
       },
       {
          "city":"Valle De San Juan",
          "postalCode":"73854"
       },
       {
          "city":"Venadillo",
          "postalCode":"73861"
       },
       {
          "city":"Villahermosa",
          "postalCode":"73870"
       },
       {
          "city":"Villarrica",
          "postalCode":"73873"
       }
    ]
 },
 {
    "state":"Valle Del Cauca",
    "item":[
       {
          "city":"Alcalá",
          "postalCode":"76020"
       },
       {
          "city":"Andalucía",
          "postalCode":"76036"
       },
       {
          "city":"Ansermanuevo",
          "postalCode":"76041"
       },
       {
          "city":"Argelia",
          "postalCode":"76054"
       },
       {
          "city":"Bolívar",
          "postalCode":"76100"
       },
       {
          "city":"Buenaventura",
          "postalCode":"76109"
       },
       {
          "city":"Bugalagrande",
          "postalCode":"76113"
       },
       {
          "city":"Caicedonia",
          "postalCode":"76122"
       },
       {
          "city":"Cali",
          "postalCode":"76001"
       },
       {
          "city":"Calima",
          "postalCode":"76126"
       },
       {
          "city":"Candelaria",
          "postalCode":"76130"
       },
       {
          "city":"Cartago",
          "postalCode":"76147"
       },
       {
          "city":"Dagua",
          "postalCode":"76233"
       },
       {
          "city":"El Águila",
          "postalCode":"76243"
       },
       {
          "city":"El Cairo",
          "postalCode":"76246"
       },
       {
          "city":"El Cerrito",
          "postalCode":"76248"
       },
       {
          "city":"El Dovio",
          "postalCode":"76250"
       },
       {
          "city":"Florida",
          "postalCode":"76275"
       },
       {
          "city":"Ginebra",
          "postalCode":"76306"
       },
       {
          "city":"Guacarí",
          "postalCode":"76318"
       },
       {
          "city":"Guadalajara De Buga",
          "postalCode":"76111"
       },
       {
          "city":"Jamundí",
          "postalCode":"76364"
       },
       {
          "city":"La Cumbre",
          "postalCode":"76377"
       },
       {
          "city":"La Unión",
          "postalCode":"76400"
       },
       {
          "city":"La Victoria",
          "postalCode":"76403"
       },
       {
          "city":"Obando",
          "postalCode":"76497"
       },
       {
          "city":"Palmira",
          "postalCode":"76520"
       },
       {
          "city":"Pradera",
          "postalCode":"76563"
       },
       {
          "city":"Restrepo",
          "postalCode":"76606"
       },
       {
          "city":"Riofrío",
          "postalCode":"76616"
       },
       {
          "city":"Roldanillo",
          "postalCode":"76622"
       },
       {
          "city":"San Pedro",
          "postalCode":"76670"
       },
       {
          "city":"Sevilla",
          "postalCode":"76736"
       },
       {
          "city":"Toro",
          "postalCode":"76823"
       },
       {
          "city":"Trujillo",
          "postalCode":"76828"
       },
       {
          "city":"Tuluá",
          "postalCode":"76834"
       },
       {
          "city":"Ulloa",
          "postalCode":"76845"
       },
       {
          "city":"Versalles",
          "postalCode":"76863"
       },
       {
          "city":"Vijes",
          "postalCode":"76869"
       },
       {
          "city":"Yotoco",
          "postalCode":"76890"
       },
       {
          "city":"Yumbo",
          "postalCode":"76892"
       },
       {
          "city":"Zarzal",
          "postalCode":"76895"
       }
    ]
 },
 {
    "state":"Vaupés",
    "item":[
       {
          "city":"Carurú",
          "postalCode":"97161"
       },
       {
          "city":"Mitú",
          "postalCode":"97001"
       },
       {
          "city":"Pacoa",
          "postalCode":"97511"
       },
       {
          "city":"Papunaua",
          "postalCode":"97777"
       },
       {
          "city":"Taraira",
          "postalCode":"97666"
       },
       {
          "city":"Yavaraté",
          "postalCode":"97889"
       }
    ]
 },
 {
    "state":"Vichada",
    "item":[
       {
          "city":"Cumaribo",
          "postalCode":"99773"
       },
       {
          "city":"La Primavera",
          "postalCode":"99524"
       },
       {
          "city":"Puerto Carreño",
          "postalCode":"99001"
       },
       {
          "city":"Santa Rosalía",
          "postalCode":"99624"
       }
    ]
 },
 
 
];
